linters:
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    - misspell
    - whitespace
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - cyclop
    - staticcheck
    - unused
  