name: BUILD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint-go:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: false
      
      # - name: Tidy Go modules
      #   run: go mod tidy
      #   working-directory: ./backend
        
      - name: Install dependencies
        run: go get .
        working-directory: ./backend

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.57
          working-directory: ./backend

      - name: Build
        run: go build -v ./...
      
      - name: Test with the Go CLI
        run: go test
    
  lint-ts:
    name: Lint TypeScript Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      # The "Set permissions" step might not be necessary since "npx" is being used to run ESLint,
      # but if your CI environment requires this, keep it. Otherwise, it can be safely removed.
      - name: Set permissions
        run: chmod +x ./node_modules/.bin/eslint
      
      - name: Run ESLint
        run: npx eslint .

  test-ts:
    name: Test TypeScript/React Code
    needs: lint-ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm test
      