name: BUILD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint-go:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      
      - name: Tidy Go modules
        run: go mod tidy
        working-directory: ./backend
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: 'latest'
  
  test-go:
    name: Test Go Code
    needs: lint-go
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run Go tests
        run: go test ./...
    
  lint-ts:
    name: Lint TypeScript Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm install
      
      # The "Set permissions" step might not be necessary since "npx" is being used to run ESLint,
      # but if your CI environment requires this, keep it. Otherwise, it can be safely removed.
      - name: Set permissions
        run: chmod +x ./node_modules/.bin/eslint
      
      - name: Run ESLint
        run: npx eslint .

  test-ts:
    name: Test TypeScript/React Code
    needs: lint-ts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Run Jest Tests
        run: npm test
      