name: BUILD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
    # Required: allow read access to the content for analysis.
    contents: read
    # Optional: allow read access to pull request. Use with `only-new-issues` option.
    pull-requests: read
    # Optional: Allow write access to checks to allow the action to annotate code in the PR.
    checks: write

jobs:
  lint-go:
    name: Lint Go Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'
      - name: Tidy Go modules
        run: go mod tidy
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          # Require: The version of golangci-lint to use.
          # When `install-mode` is `binary` (default) the value can be v1.2 or v1.2.3 or `latest` to use the latest version.
          # When `install-mode` is `goinstall` the value can be v1.2.3, `latest`, or the hash of a commit.
          version: v1.54

  lint-ts:
    name: Lint TypeScript Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Set permissions
        run: chmod +x ./node_modules/.bin/eslint      
      - name: Run ESLint
        run: npx eslint .